### ISSUE TITLE
why mean_value is different between training and deploy process ?

### ISSUE THREAD

**Issue by embedeepLHY** [eric612/MobileNet-YOLO#100]
mean_value in training process is 127.5. However, 1.0 is used in deploy process, Why?

**Comment by eric612** [comment]
You can refer to this [link](https://github.com/eric612/MobileNet-YOLO/wiki/Subtract-and-normalize)

The reason is in [example](https://github.com/eric612/MobileNet-YOLO/blob/master/examples/yolo/yolo_detect.cpp#L499-L501) , it can both do resize and normalize , and subtraction after resize can reduce some computation , but it might not be best solution , you can reference ncnn [pre-process](https://github.com/Tencent/ncnn/blob/master/examples/peleenetssd_seg.cpp#L56)

**Comment by embedeepLHY** [comment]
I get it! Thanks!
