### ISSUE TITLE
Build error with linking CXX executable

### ISSUE THREAD

**Issue by xi3299** [eric612/MobileNet-YOLO#111]
Hello, when I run `make -j4`, I met this problem. Does anyone know how to fix that?

> [77%] Built target caffe
> [ 77%] Linking CXX executable upgrade_net_proto_binary
> ../lib/libcaffe.so.1.0.0: undefined reference to `cv::VideoWriter::write(cv::Mat const&)'
> ../lib/libcaffe.so.1.0.0: undefined reference to `cv::VideoWriter::VideoWriter(cv::String const&, int, double, cv::Size_<int>, bool)'
> ../lib/libcaffe.so.1.0.0: undefined reference to `cv::VideoWriter::VideoWriter()'
> ../lib/libcaffe.so.1.0.0: undefined reference to `cv::VideoWriter::isOpened() const'
> ../lib/libcaffe.so.1.0.0: undefined reference to `cv::VideoWriter::~VideoWriter()'
> collect2: error: ld returned 1 exit status
> tools/CMakeFiles/upgrade_net_proto_binary.dir/build.make:128: recipe for target 'tools/upgrade_net_proto_binary' failed
> make[2]: *** [tools/upgrade_net_proto_binary] Error 1
> CMakeFiles/Makefile2:465: recipe for target 'tools/CMakeFiles/upgrade_net_proto_binary.dir/all' failed
> make[1]: *** [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error

**Comment by xi3299** [comment]
I solved this issue by changing the opencv version (opencv3.3).

**Comment by ginomempin** [comment]
I also experienced this even when using the correct OpenCV 3.3 version.  
For me, it was because I was using a non-default OpenCV installation path: **/usr/local/opencv/3.3.1/** instead of the default **/usr/local**.

To fix the build errors, I needed to update some of the CMake files.
See https://github.com/eric612/MobileNet-YOLO/issues/73#issuecomment-506580259
