### ISSUE TITLE
Train YOLO V3 on VisDrone dataset

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [eric612/MobileNet-YOLO#162]
I want to train YOLO V3  for object detection on VisDrone dataset which contains images with size about 540 x 960 P etc . and their annotations accordingly,  however  for the YOLO V3 training I want to resize all the images to 416 x 416 and also change Annotations accordingly . 

Is there any method or suggestions to do it ?  
If I just resize all the images to 416 x 416 P and use the original annotations is it ok or I must change the annotations if i change the size?

**Comment by eric612** [comment]
The annotations will be normalize to range 0~1 , so it is independent with the image size . 

But , you need care about the aspect ratio , because all your images were  9:16, which is very different with other dataset , here is the suggest ways : 
1. Re-calculation anchors 
2. Train and test image with aspect ratio 9:16, for example : 270x480
