### ISSUE TITLE
How to calculate the mAP of darknet-yolov3?

### ISSUE THREAD

**Issue by DeepPower** [eric612/MobileNet-YOLO#26]
Hello!Thanks for your work.Could you please tell me the way to calculate the mAP of darknet-yolov3?

**Comment by eric612** [comment]
Here was a template , you can use yolov3 instead of yolov3-spp
[solover](https://github.com/eric612/MobileNet-YOLO/blob/master/models/darknet_yolov3/solver.prototxt),[test](https://github.com/eric612/MobileNet-YOLO/blob/master/models/darknet_yolov3/yolov3-spp-test.prototxt),[train](https://github.com/eric612/MobileNet-YOLO/blob/master/models/darknet_yolov3/yolov3-spp-train.prototxt)

**Comment by DeepPower** [comment]
Effective, thanks a lot.
