### ISSUE TITLE
Coordinary loss function of region_layer 

### ISSUE THREAD

**Issue by litingsjj** [eric612/MobileNet-YOLO#43]
Hi, thanks for your code. I have a question about coordinary loss function of region layer. Compare yolov3, why loss x is`delta[index + 0 * stride] = (-1) * scale * (tx - sigmoid(x[index + 0 * stride])) * sigmoid(x[index + 0 * stride]) * (1 - sigmoid(x[index + 0 * stride]));` ? And in yolov3 `delta[index + 0 * stride] = (-1) * scale * (tx - x[index + 0 * stride])`, I know `x[index + 0 * stride]=logistic_activate(input_data[index2 + 0])`. So yolov2 coordinary loss is calculating with `delta[index + 0 * stride] = (-1) * scale * (tx - sigmoid(x[index + 0 * stride]))`, what's means of `sigmoid(x[index + 0 * stride]) * (1 - sigmoid(x[index + 0 * stride]))` ?

**Comment by eric612** [comment]
I put logic_gradient on backward function in [yolov3](https://github.com/eric612/MobileNet-YOLO/blob/master/src/caffe/layers/yolov3_layer.cpp) , however , yolov3 do not use this term , due to [maxima likelyhood](https://zlatankr.github.io/posts/2017/03/06/mle-gradient-descent) , In order to understand my code easily , so I keep it

* logic_gradient = logic_activate(x) * (1 - logic_activate(x])

**Comment by litingsjj** [comment]
@eric612  Sorry, still don't understand `diff[index + 4 * stride] = (-1) * noobject_scale_ * (0 - swap_data[index + 4 * stride]) *logistic_gradient(swap_data[index + 4 * stride]);` why not `//diff[index + 4] = (-1) * noobject_scale_* (0 - swap_data[index + 4]);`?

**Comment by eric612** [comment]
The first term you write was the original code from [darknet](https://github.com/pjreddie/darknet/blob/c6afc7ff1499fbbe64069e1843d7929bd7ae2eaa/src/region_layer.c) , the region layer of this project was base on the old version of darknet .
