### ISSUE TITLE
why adding maxpooling layer after deconvolution layer in yolov3_lite ?

### ISSUE THREAD

**Issue by louyanyang** [eric612/MobileNet-YOLO#98]
hi @eric612 ,  read your mobilenet_yolov3_lite_train.prototxt, i don't understand the process, as i known, deconvolution adds featuremap size ,after it, but,  why adding maxpooling? if so, deconvolution makes no sense.

**Comment by eric612** [comment]
Because the deconvolution layer cost so much computing , even if I change the kernel size 4 to 2 .
And you can see this [issue](https://github.com/eric612/MobileNet-YOLO/issues/29) , It doesn't matter what upsample used when training object detection . So I set kernel to 1 (or use the nearest upsample) , but , however , the dimension (w,h) will be decrease and the value does not fill all tensors. The maxpooling layer solved this two problems .

**Comment by louyanyang** [comment]
@eric612 ok, i see. thanks for your design detail.
